### ISSUE TITLE
How to make piano tuner

### ISSUE THREAD

**Issue by jijkbird** [scidart/scidart_examples#6]
I'm trying to make a piano tuner

Using sound_ Stream for recording

How to convert PCM 16bit mono uint8list to audio,

I'm trying to compare audio frequencies

**Comment by polotto** [comment]
Amazing! Are you planning to make a PR to contribute here?

**Comment by jijkbird** [comment]
what's PR?

**Comment by polotto** [comment]
PR = Pull Request, a resource to contribute with new codes

**Comment by jijkbird** [comment]
I used other plug-ins and didn't implement the code myself.

**Comment by polotto** [comment]
Do you used SciDart to solve some problem in your code? I'm interest in that to expand the SciDart examples gallery.

**Comment by jijkbird** [comment]
I want to use it, but I don't know how to use it.

**Comment by polotto** [comment]
You can follow this example: https://github.com/scidart/scidart_examples#frequency-estimator
